#!/bin/bash
mkdir five

for folder_index in {1..5}
do
        mkdir five/dir$folder_index
        for file_index in {1..5}
        do
                touch five/dir$folder_index/file$file_index
                for line in $(seq $file_index)
                do
                        echo $file_index >> five/dir$folder_index/file$file_index
                done
        done
done
